version: '3.1'

services:
  db:
    image: postgres
    container_name: dbSql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: change_me
      POSTGRES_USER: admin
      POSTGRES_DB: mediscreen_sql
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9090:8080

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb


  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  microservice.patient:
    build: ./patientApi
    container_name: patient_ms
    ports:
      - 8081:8081
    depends_on:
      - db


  microservice.patientmedicalhistory:
    build: ./patientMedicalHistory-Microservice
    container_name: medicalHistory_ms
    ports:
      - 8082:8082
    depends_on:
      - mongo

  microservice.patientui:
    build: ./patientui
    container_name: ui_ms
    ports:
      - 8080:8080
    depends_on:
      - microservice.patientmedicalhistory
      - microservice.patient

volumes:
  postgresqldata:
  mongodata:
  mongoconfig: